# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: resources
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

custom:
  name: resources
  serverless-offline:
    httpPort: 4000
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
      stages:
        - local
      start:
        port: 4001
        migrate: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, 'local'}
  environment:
    STAGE: ${self:provider.stage} 

    # Only have one key for all environments
    API_DNI_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InllZnJpb3NjYXI5ODE0QGdtYWlsLmNvbSJ9.JViUp355LIb0ax7C8U-PpPkHbKFTGJ3_rcsliRDhALg
    API_DNI_URL: https://dniruc.apisperu.com/api/v1/dni

    # DynamoDB Tables
    # [Name of service]-[Name of stage]-[Name of table]
    # Example: resources-dev-user
    USER_TABLE: ${self:service}-${self:provider.stage}-user

functions:
  verifiedDni:
    handler: handler.verifiedDni
    events:
      - http:
          path: verified-dni
          method: post

  getDepartments:
    handler: handler.getDepartments
    events:
      - http:
          path: departments
          method: get

  getProvinces:
    handler: handler.getProvinces
    events:
      - http:
          path: provinces/{departmentCode}
          method: get

  getDistricts:
    handler: handler.getDistricts
    events:
      - http:
          path: districts/{provinceCode}
          method: get

resources:
  # Api Gateway
  - ${file(./api-gateway.yml)}
  
  # DynamoDb Tables
  - ${file(./dynamodb-tables.yml)}

plugins:
  - serverless-dynamodb-local
  - serverless-webpack
  - serverless-offline
